### ISSUE TITLE
Chapter 11 null 대신 Optional 클래스

### ISSUE THREAD

**Issue by doxxx93** [study-mji/ModernJavaInActionStudy#13]
https://velog.io/@doxxx93/modern-java-in-action-chap11

**Comment by Raemerrr** [comment]
https://fish-hoodie-b32.notion.site/11-null-Optional-1f5c15ef611f4d969aa7173e12e13ee6

**Comment by Tianea2160** [comment]
https://magical-fluorine-7a0.notion.site/chapter-11-null-Optional-b1df5e2a4e804d9bb5291815ab163d1b

**Comment by jojiapp** [comment]
https://jojiapp.github.io/blog/java/Modern-Java-in-Action/part-4-%EB%A7%A4%EC%9D%BC-%EC%9E%90%EB%B0%94%EC%99%80-%ED%95%A8%EA%BB%98/Chapter-11-null-%EB%8C%80%EC%8B%A0-Optional-%ED%81%B4%EB%9E%98%EC%8A%A4
