### ISSUE TITLE
Chapter 13 default method

### ISSUE THREAD

**Issue by Tianea2160** [study-mji/ModernJavaInActionStudy#15]

**Comment by Tianea2160** [comment]
https://magical-fluorine-7a0.notion.site/default-method-080d2aa721da4962b0cdf8c73e282c85

**Comment by doxxx93** [comment]
https://velog.io/@doxxx93/mji13

**Comment by Raemerrr** [comment]
https://fish-hoodie-b32.notion.site/13-5f4ff1b08f63436c84da76ecbb3d3c0b

**Comment by jojiapp** [comment]
https://jojiapp.github.io/blog/java/Modern-Java-in-Action/part-4-매일-자바와-함께/Chapter-13-디폴트-메소드
