### ISSUE TITLE
Chapter 18 함수형 관점으로 생각하기

### ISSUE THREAD

**Issue by Tianea2160** [study-mji/ModernJavaInActionStudy#18]

**Comment by doxxx93** [comment]
https://velog.io/@doxxx93/mja18

**Comment by Raemerrr** [comment]
https://fish-hoodie-b32.notion.site/18-921503f75b264d29bc0514a94714e5ba

**Comment by jojiapp** [comment]
https://jojiapp.github.io/blog/Book/Modern-Java-In-Action/part-6-함수형-프로그래밍과-자바-진화의-미래/Chapter-18-함수형-관점으로-생각하기
