### ISSUE TITLE
Chapter 5 스트림 활용

### ISSUE THREAD

**Issue by Tianea2160** [study-mji/ModernJavaInActionStudy#5]
각자 챕터5를 읽고 자유롭게 요약 및 공부해서 링크를 올려주시면 됩니다.

**Comment by jojiapp** [comment]
https://chill-dove-7c6.notion.site/Chapter5-2a12be6813654c9fa14afa6388f26589

**Comment by Tianea2160** [comment]
https://magical-fluorine-7a0.notion.site/chapter-5-ccc2ed786b2c4cf2ab6605f30396c77f

**Comment by doxxx93** [comment]
https://velog.io/@doxxx93/%EB%AA%A8%EB%8D%98-%EC%9E%90%EB%B0%94-%EC%9D%B8-%EC%95%A1%EC%85%98-5

**Comment by dding94** [comment]
https://valley-road-6eb.notion.site/0f6fdef55ce44006b8d6f16ac373165b
