### ISSUE TITLE
Chapter 6 스트림으로 데이터 수집

### ISSUE THREAD

**Issue by Tianea2160** [study-mji/ModernJavaInActionStudy#6]

**Comment by jojiapp** [comment]
https://chill-dove-7c6.notion.site/Chapter6-b8725af42faf419a82f040039e015d84

**Comment by Tianea2160** [comment]
https://magical-fluorine-7a0.notion.site/chapter-6-22979ad8de7e41ec8335bab305e23c09

**Comment by Raemerrr** [comment]
https://fish-hoodie-b32.notion.site/6-ab304c5223bc4fc29c5da5af4d548d98

**Comment by dding94** [comment]
https://valley-road-6eb.notion.site/0f6fdef55ce44006b8d6f16ac373165b
