### ISSUE TITLE
Chapter 8 컬렉션 API 개선

### ISSUE THREAD

**Issue by Raemerrr** [study-mji/ModernJavaInActionStudy#8]
https://fish-hoodie-b32.notion.site/8-API-491e96fd6d7b4d91b0840cfc4a9aca48

**Comment by doxxx93** [comment]
https://velog.io/@doxxx93/%EB%AA%A8%EB%8D%98-%EC%9E%90%EB%B0%94-%EC%9D%B8-%EC%95%A1%EC%85%98-Chap-08.-%EC%BB%AC%EB%A0%89%EC%85%98-API-%EA%B0%9C%EC%84%A0

**Comment by jojiapp** [comment]
https://jojiapp.github.io/til/java/Modern-Java-in-Action/part-3-%EC%8A%A4%ED%8A%B8%EB%A6%BC%EA%B3%BC-%EB%9E%8C%EB%8B%A4%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%ED%9A%A8%EA%B3%BC%EC%A0%81-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D/Chapter-8-%EC%BB%AC%EB%A0%89%EC%85%98-API-%EA%B0%9C%EC%84%A0
